`timescale 1ns / 1ps

// rv32i_top_tb.sv
// Integration testbench for the full single-cycle datapath.
//
// Runs a hand-assembled RV32I program (rv32i_top_program.hex, generated by
// a small Python assembler/reference-simulator so the expected values below
// are cross-checked against an independent model rather than hand math) that
// exercises every instruction category: R-type and I-type ALU ops, LUI,
// AUIPC, all load/store widths, all six branch types (taken and not-taken),
// JAL and JALR, ending in a self-loop (JAL x0,0) that acts as a halt.
//
// Because this is a single-cycle core, exactly one instruction retires per
// clock edge, so the expected register-file write (if any) and the expected
// next PC are checked immediately after every single edge - this catches a
// wrong result the moment it's produced, even for a register that a later
// instruction in the program deliberately reuses as scratch space.

module rv32i_top_tb;

    logic clk;
    logic reset;

    int errors = 0;
    int checks = 0;

    rv32i_top #(
        .INSTR_INIT_FILE ("rv32i_top_program.hex")
    ) dut (
        .clk   (clk),
        .reset (reset)
    );

    // 10ns period clock
    initial clk = 0;
    always #5 clk = ~clk;

    // ---------------- expected per-cycle trace ----------------
    // Generated from a reference Python model of the same program; see
    // scratchpad asm.py used to produce rv32i_top_program.hex.
    localparam int N_STEPS = 53;

    logic [31:0] exp_pc   [0:N_STEPS-1];
    int          exp_rd   [0:N_STEPS-1];
    logic [31:0] exp_val  [0:N_STEPS-1];
    bit          exp_write[0:N_STEPS-1];

    initial begin
        exp_pc[0]='h004; exp_rd[0]= 1; exp_val[0]=32'h00000005; exp_write[0]=1; // [0] addr=  0: ADDI x1, x0, 5
        exp_pc[1]='h008; exp_rd[1]= 2; exp_val[1]=32'h0000000A; exp_write[1]=1; // [1] addr=  4: ADDI x2, x0, 10
        exp_pc[2]='h00C; exp_rd[2]= 3; exp_val[2]=32'hFFFFFFFD; exp_write[2]=1; // [2] addr=  8: ADDI x3, x0, -3
        exp_pc[3]='h010; exp_rd[3]= 4; exp_val[3]=32'h0000000F; exp_write[3]=1; // [3] addr= 12: ADD  x4, x1, x2
        exp_pc[4]='h014; exp_rd[4]= 5; exp_val[4]=32'h00000005; exp_write[4]=1; // [4] addr= 16: SUB  x5, x2, x1
        exp_pc[5]='h018; exp_rd[5]= 6; exp_val[5]=32'h00000000; exp_write[5]=1; // [5] addr= 20: AND  x6, x1, x2
        exp_pc[6]='h01C; exp_rd[6]= 7; exp_val[6]=32'h0000000F; exp_write[6]=1; // [6] addr= 24: OR   x7, x1, x2
        exp_pc[7]='h020; exp_rd[7]= 8; exp_val[7]=32'h0000000F; exp_write[7]=1; // [7] addr= 28: XOR  x8, x1, x2
        exp_pc[8]='h024; exp_rd[8]= 9; exp_val[8]=32'h00000001; exp_write[8]=1; // [8] addr= 32: SLT  x9, x1, x2
        exp_pc[9]='h028; exp_rd[9]=10; exp_val[9]=32'h00000000; exp_write[9]=1; // [9] addr= 36: SLT  x10, x2, x1
        exp_pc[10]='h02C; exp_rd[10]=11; exp_val[10]=32'h00000000; exp_write[10]=1; // [10] addr= 40: SLTU x11, x3, x1
        exp_pc[11]='h030; exp_rd[11]=12; exp_val[11]=32'h00001400; exp_write[11]=1; // [11] addr= 44: SLL  x12, x1, x2
        exp_pc[12]='h034; exp_rd[12]=13; exp_val[12]=32'h00000005; exp_write[12]=1; // [12] addr= 48: SRL  x13, x12, x2
        exp_pc[13]='h038; exp_rd[13]=14; exp_val[13]=32'hFFFFFFFF; exp_write[13]=1; // [13] addr= 52: SRA  x14, x3, x2
        exp_pc[14]='h03C; exp_rd[14]=15; exp_val[14]=32'h00000002; exp_write[14]=1; // [14] addr= 56: ANDI x15, x2, 6
        exp_pc[15]='h040; exp_rd[15]=16; exp_val[15]=32'h0000000F; exp_write[15]=1; // [15] addr= 60: ORI  x16, x2, 5
        exp_pc[16]='h044; exp_rd[16]=17; exp_val[16]=32'h0000000F; exp_write[16]=1; // [16] addr= 64: XORI x17, x2, 5
        exp_pc[17]='h048; exp_rd[17]=18; exp_val[17]=32'h00000001; exp_write[17]=1; // [17] addr= 68: SLTI x18, x1, 10
        exp_pc[18]='h04C; exp_rd[18]=19; exp_val[18]=32'h00000001; exp_write[18]=1; // [18] addr= 72: SLTIU x19, x1, 10
        exp_pc[19]='h050; exp_rd[19]=20; exp_val[19]=32'h00000014; exp_write[19]=1; // [19] addr= 76: SLLI x20, x1, 2
        exp_pc[20]='h054; exp_rd[20]=21; exp_val[20]=32'h00000005; exp_write[20]=1; // [20] addr= 80: SRLI x21, x20, 2
        exp_pc[21]='h058; exp_rd[21]=22; exp_val[21]=32'hFFFFFFFE; exp_write[21]=1; // [21] addr= 84: SRAI x22, x3, 1
        exp_pc[22]='h05C; exp_rd[22]=23; exp_val[22]=32'h12345000; exp_write[22]=1; // [22] addr= 88: LUI  x23, 0x12345
        exp_pc[23]='h060; exp_rd[23]=24; exp_val[23]=32'h0000105C; exp_write[23]=1; // [23] addr= 92: AUIPC x24, 1
        exp_pc[24]='h064; exp_rd[24]=25; exp_val[24]=32'h00000040; exp_write[24]=1; // [24] addr= 96: ADDI x25, x0, 64
        exp_pc[25]='h068; exp_rd[25]= 0; exp_val[25]=32'h00000000; exp_write[25]=0; // [25] addr=100: SW   x4, 0(x25)
        exp_pc[26]='h06C; exp_rd[26]= 0; exp_val[26]=32'h00000000; exp_write[26]=0; // [26] addr=104: SH   x1, 4(x25)
        exp_pc[27]='h070; exp_rd[27]= 0; exp_val[27]=32'h00000000; exp_write[27]=0; // [27] addr=108: SB   x2, 8(x25)
        exp_pc[28]='h074; exp_rd[28]=26; exp_val[28]=32'h0000000F; exp_write[28]=1; // [28] addr=112: LW   x26, 0(x25)
        exp_pc[29]='h078; exp_rd[29]=27; exp_val[29]=32'h00000005; exp_write[29]=1; // [29] addr=116: LH   x27, 4(x25)
        exp_pc[30]='h07C; exp_rd[30]=28; exp_val[30]=32'h0000000A; exp_write[30]=1; // [30] addr=120: LB   x28, 8(x25)
        exp_pc[31]='h080; exp_rd[31]=29; exp_val[31]=32'h0000000A; exp_write[31]=1; // [31] addr=124: LBU  x29, 8(x25)
        exp_pc[32]='h084; exp_rd[32]=30; exp_val[32]=32'h00000005; exp_write[32]=1; // [32] addr=128: LHU  x30, 4(x25)
        exp_pc[33]='h088; exp_rd[33]= 0; exp_val[33]=32'h00000000; exp_write[33]=0; // [33] addr=132: SW   x3, 12(x25)
        exp_pc[34]='h08C; exp_rd[34]=31; exp_val[34]=32'hFFFFFFFD; exp_write[34]=1; // [34] addr=136: LW   x31, 12(x25)
        exp_pc[35]='h094; exp_rd[35]= 0; exp_val[35]=32'h00000000; exp_write[35]=0; // [35] addr=140: BEQ  x1, x1, beq_target (taken)
        exp_pc[36]='h098; exp_rd[36]= 6; exp_val[36]=32'h0000006F; exp_write[36]=1; // [36] addr=148: ADDI x6, x0, 111  (branch target - x6 reused)
        exp_pc[37]='h09C; exp_rd[37]= 0; exp_val[37]=32'h00000000; exp_write[37]=0; // [37] addr=152: BNE  x1, x1, bne_target (not taken)
        exp_pc[38]='h0A0; exp_rd[38]= 7; exp_val[38]=32'h000000DE; exp_write[38]=1; // [38] addr=156: ADDI x7, x0, 222  (fallthrough - x7 reused)
        exp_pc[39]='h0A8; exp_rd[39]= 0; exp_val[39]=32'h00000000; exp_write[39]=0; // [39] addr=160: BLT  x1, x2, blt_target (taken)
        exp_pc[40]='h0AC; exp_rd[40]= 8; exp_val[40]=32'h000001BC; exp_write[40]=1; // [40] addr=168: ADDI x8, x0, 444  (branch target - x8 reused)
        exp_pc[41]='h0B4; exp_rd[41]= 0; exp_val[41]=32'h00000000; exp_write[41]=0; // [41] addr=172: BGE  x2, x1, bge_target (taken)
        exp_pc[42]='h0B8; exp_rd[42]= 9; exp_val[42]=32'h0000022B; exp_write[42]=1; // [42] addr=180: ADDI x9, x0, 555  (branch target - x9 reused)
        exp_pc[43]='h0BC; exp_rd[43]= 0; exp_val[43]=32'h00000000; exp_write[43]=0; // [43] addr=184: BLTU x3, x1, bltu_target (not taken)
        exp_pc[44]='h0C0; exp_rd[44]=10; exp_val[44]=32'h0000029A; exp_write[44]=1; // [44] addr=188: ADDI x10, x0, 666 (fallthrough - x10 reused)
        exp_pc[45]='h0C8; exp_rd[45]= 0; exp_val[45]=32'h00000000; exp_write[45]=0; // [45] addr=192: BGEU x3, x1, bgeu_target (taken)
        exp_pc[46]='h0CC; exp_rd[46]=11; exp_val[46]=32'h00000309; exp_write[46]=1; // [46] addr=200: ADDI x11, x0, 777 (branch target - x11 reused)
        exp_pc[47]='h0D4; exp_rd[47]=12; exp_val[47]=32'h000000D0; exp_write[47]=1; // [47] addr=204: JAL  x12, jal_target
        exp_pc[48]='h0D8; exp_rd[48]=13; exp_val[48]=32'h00000378; exp_write[48]=1; // [48] addr=212: ADDI x13, x0, 888 (JAL target - x13 reused)
        exp_pc[49]='h0DC; exp_rd[49]=14; exp_val[49]=32'h000000E4; exp_write[49]=1; // [49] addr=216: ADDI x14, x0, jalr_target (absolute addr, for JALR)
        exp_pc[50]='h0E4; exp_rd[50]=15; exp_val[50]=32'h000000E0; exp_write[50]=1; // [50] addr=220: JALR x15, x14, 0
        exp_pc[51]='h0E8; exp_rd[51]=16; exp_val[51]=32'h0000006F; exp_write[51]=1; // [51] addr=228: ADDI x16, x0, 111 (JALR target - x16 reused)
        exp_pc[52]='h0E8; exp_rd[52]= 0; exp_val[52]=32'h00000000; exp_write[52]=0; // [52] addr=232: JAL  x0, halt (self-loop)
    end

    // Final architectural state, as an independent cross-check against the
    // per-cycle trace above (also confirms nothing later clobbers a
    // register that shouldn't have been touched again).
    logic [31:0] exp_final_regs[0:31];
    initial begin
        exp_final_regs[0]  = 32'h00000000;
        exp_final_regs[1]  = 32'h00000005;
        exp_final_regs[2]  = 32'h0000000A;
        exp_final_regs[3]  = 32'hFFFFFFFD;
        exp_final_regs[4]  = 32'h0000000F;
        exp_final_regs[5]  = 32'h00000005;
        exp_final_regs[6]  = 32'h0000006F;
        exp_final_regs[7]  = 32'h000000DE;
        exp_final_regs[8]  = 32'h000001BC;
        exp_final_regs[9]  = 32'h0000022B;
        exp_final_regs[10] = 32'h0000029A;
        exp_final_regs[11] = 32'h00000309;
        exp_final_regs[12] = 32'h000000D0;
        exp_final_regs[13] = 32'h00000378;
        exp_final_regs[14] = 32'h000000E4;
        exp_final_regs[15] = 32'h000000E0;
        exp_final_regs[16] = 32'h0000006F;
        exp_final_regs[17] = 32'h0000000F;
        exp_final_regs[18] = 32'h00000001;
        exp_final_regs[19] = 32'h00000001;
        exp_final_regs[20] = 32'h00000014;
        exp_final_regs[21] = 32'h00000005;
        exp_final_regs[22] = 32'hFFFFFFFE;
        exp_final_regs[23] = 32'h12345000;
        exp_final_regs[24] = 32'h0000105C;
        exp_final_regs[25] = 32'h00000040;
        exp_final_regs[26] = 32'h0000000F;
        exp_final_regs[27] = 32'h00000005;
        exp_final_regs[28] = 32'h0000000A;
        exp_final_regs[29] = 32'h0000000A;
        exp_final_regs[30] = 32'h00000005;
        exp_final_regs[31] = 32'hFFFFFFFD;
    end

    // Bytes actually written by the SW/SH/SB block, base address = 64.
    // Only the bytes each store instruction touches are checked here -
    // data_mem has no reset/initial value, so an untouched byte (e.g. the
    // upper half of the SH at addr 68, or the upper 3 bytes of the SB at
    // addr 72) legitimately reads back as X, not 0. Those partial writes
    // were already exercised end-to-end by the LH/LB/LBU/LHU per-cycle
    // checks above (steps 29-32), which only ever read back the bytes that
    // were actually written.

    localparam logic [31:0] HALT_PC = 32'h000000E8; // address of the JAL x0,halt self-loop

    // ---------------- checking tasks ----------------
    task automatic check_pc(input int idx, input logic [31:0] expected);
        checks++;
        if (dut.pc_current !== expected) begin
            errors++;
            $display("FAIL [step %0d] pc_current expected=%0h got=%0h", idx, expected, dut.pc_current);
        end
    endtask

    task automatic check_reg(input int idx, input int rd, input logic [31:0] expected);
        checks++;
        if (dut.regfile.regs[rd] !== expected) begin
            errors++;
            $display("FAIL [step %0d] regs[x%0d] expected=%0h got=%0h", idx, rd, expected, dut.regfile.regs[rd]);
        end
    endtask

    initial begin
        // ---------------- reset ----------------
        reset = 1'b1;
        @(posedge clk);
        reset = 1'b0;

        // ---------------- run the program, one instruction per edge ----------------
        for (int i = 0; i < N_STEPS; i++) begin
            @(posedge clk);
            #1; // let combinational logic settle after the edge
            check_pc(i, exp_pc[i]);
            if (exp_write[i]) begin
                check_reg(i, exp_rd[i], exp_val[i]);
            end
        end
        if (errors == 0)
            $display("PASS: all %0d per-cycle checks matched through instruction retirement", checks);

        // ---------------- confirm the halt self-loop holds PC steady ----------------
        for (int i = 0; i < 3; i++) begin
            @(posedge clk);
            #1;
            checks++;
            if (dut.pc_current !== HALT_PC) begin
                errors++;
                $display("FAIL [halt hold %0d] pc_current expected=%0h got=%0h", i, HALT_PC, dut.pc_current);
            end
        end
        if (errors == 0)
            $display("PASS: CPU parked at halt loop (pc=%0h)", HALT_PC);

        // ---------------- final architectural register-file check ----------------
        // x1..x31 only - x0's hardwired-zero behavior is register.sv's own concern
        // and is already covered by register_tb.sv.
        for (int r = 1; r < 32; r++) begin
            checks++;
            if (dut.regfile.regs[r] !== exp_final_regs[r]) begin
                errors++;
                $display("FAIL [final regs] x%0d expected=%0h got=%0h", r, exp_final_regs[r], dut.regfile.regs[r]);
            end
        end
        if (errors == 0)
            $display("PASS: final register file matches expected architectural state");

        // ---------------- final data memory check ----------------
        // mem[64:67] <- SW x4 (15), full word
        checks++;
        if ({dut.dmem.mem[67], dut.dmem.mem[66], dut.dmem.mem[65], dut.dmem.mem[64]} !== 32'h0000000F) begin
            errors++;
            $display("FAIL [final mem] addr=64 (word) expected=0000000f got=%0h",
                {dut.dmem.mem[67], dut.dmem.mem[66], dut.dmem.mem[65], dut.dmem.mem[64]});
        end
        // mem[68:69] <- SH x1 (5), halfword only
        checks++;
        if ({dut.dmem.mem[69], dut.dmem.mem[68]} !== 16'h0005) begin
            errors++;
            $display("FAIL [final mem] addr=68 (half) expected=0005 got=%0h",
                {dut.dmem.mem[69], dut.dmem.mem[68]});
        end
        // mem[72] <- SB x2 (10), byte only
        checks++;
        if (dut.dmem.mem[72] !== 8'h0A) begin
            errors++;
            $display("FAIL [final mem] addr=72 (byte) expected=0a got=%0h", dut.dmem.mem[72]);
        end
        // mem[76:79] <- SW x3 (-3), full word
        checks++;
        if ({dut.dmem.mem[79], dut.dmem.mem[78], dut.dmem.mem[77], dut.dmem.mem[76]} !== 32'hFFFFFFFD) begin
            errors++;
            $display("FAIL [final mem] addr=76 (word) expected=fffffffd got=%0h",
                {dut.dmem.mem[79], dut.dmem.mem[78], dut.dmem.mem[77], dut.dmem.mem[76]});
        end
        if (errors == 0)
            $display("PASS: final data memory matches expected state");

        // ---------------- summary ----------------
        $display("----------------------------------------");
        if (errors == 0)
            $display("ALL %0d CHECKS PASSED", checks);
        else
            $display("%0d OF %0d CHECKS FAILED", errors, checks);
        $display("----------------------------------------");

        $finish;
    end

endmodule
